- app/i18n/app.de.i18n.json
- app/i18n/app.en.i18n.json
- app/i18n/wallet.de.i18n.json
> improved german translation

- app/i18n/wallet.de.i18n.json
Fixed some typos and corrected hyphenation
> Improve German

- app/.meteor/.finished-upgraders
- app/client/lib/ethereum/observeBlocks.js
- app/client/lib/helpers/helperFunctions.js
- app/client/lib/helpers/templateHelpers.js
- app/client/styles/main.less
- app/client/templates/elements/compileContract.html
- app/client/templates/elements/compileContract.js
- app/client/templates/elements/eventsTable.html
- app/client/templates/elements/eventsTable.js
- app/client/templates/elements/executeContract.html
- app/client/templates/elements/executeContract.js
- app/client/templates/elements/inputs/address.html
- app/client/templates/elements/inputs/bool.html
- app/client/templates/elements/inputs/bytes.html
- app/client/templates/elements/inputs/int.html
- app/client/templates/elements/inputs/json.html
- app/client/templates/elements/inputs/string.html
- app/client/templates/elements/inputs/uint.html
- app/client/templates/views/modals/eventInfo.html
> added toSentence

- app/.meteor/.finished-upgraders
- app/.meteor/versions
- app/client/lib/ethereum/observeBlocks.js
- app/client/lib/helpers/helperFunctions.js
- app/client/lib/helpers/templateHelpers.js
- app/client/styles/main.less
- app/client/templates/elements/accountLink.html
- app/client/templates/elements/compileContract.html
- app/client/templates/elements/compileContract.js
- app/client/templates/elements/eventsTable.html
- app/client/templates/elements/eventsTable.js
- app/client/templates/elements/executeContract.html
- app/client/templates/elements/executeContract.js
- app/client/templates/elements/inputs/address.html
- app/client/templates/elements/inputs/bool.html
- app/client/templates/elements/inputs/bytes.html
- app/client/templates/elements/inputs/int.html
- app/client/templates/elements/inputs/json.html
- app/client/templates/elements/inputs/string.html
- app/client/templates/elements/inputs/uint.html
- app/client/templates/elements/transactionTable.html
- app/client/templates/views/modals/eventInfo.html
> Update master from develop

- app/client/lib/ethereum/observeCustomContracts.js
- app/client/templates/elements/eventsTable.js
Dao Hub is a good test for this: https://daohub.org/voting.html
> Fixes an issue where the wallet would freeze when opening a contract with thousands of events

- app/i18n/app.fr.i18n.json
- app/i18n/wallet.fr.i18n.json
Various improvements in the french translation.
Spelling corrections
Harmonization such as "Portefeuille" for "Wallet contract" and "Jeton" for "Token"
> Various misspelling corrections and harmonization in french translation files

- app/i18n/wallet.fr.i18n.json
Sorry for the second commit, but a few improvments.
> Minor changes in french translation file

- app/i18n/wallet.fr.i18n.json
The previous version was misleading about the contract deletion.
> Update french file

- app/client/lib/helpers/helperFunctions.js
- app/client/lib/helpers/templateHelpers.js
- app/client/templates/elements/vulnerabilities.html
- app/client/templates/views/send.html
- app/client/templates/views/send.js
* Fixes the link for the vulnerability blog post
* Fixes an issue that would prevent you from sending tokens out of a contract without ether
* Fixes an issue that would select an account you don’t own when sending tokens from a wallet contract
* Doesn’t allow you to deploy contracts from wallet contracts
> Fixes issues related to send and wallet contracts

- app/client/lib/ethereum/observeTransactions.js
- app/client/lib/helpers/helperFunctions.js
- app/client/templates/elements/compileContract.html
- app/client/templates/elements/compileContract.js
- app/client/templates/views/send.js
Token data was not being set correctly until you clicked the show more options
> token data was being incorrectly set

- app/.meteor/versions
- app/client/styles/elements.import.less
- app/client/templates/views/send.html
Updates the gas selector. Changes the default from latest block’s gas to web3.eth.gasPrice which is a median of the last N blocks. Also changes the default position and exponential factor, so that the smallest is about 1/4 of the default and the highest is about 10x the default.
> updates packages

- app/client/templates/views/send.js
> Prohibits negative 'sendAllAmount'

- app/client/lib/ethereum/observePendingConfirmations.js
- app/client/lib/ethereum/observeTransactions.js
- app/client/lib/ethereum/observeWallets.js
- app/client/mist.js
- app/client/templates/layout/header.js
This PR fixes the disappearing or not disappearing of confirmations.
> fixed confirmations not disapearing

- app/client/styles/elements.import.less
- app/client/templates/views/dashboard.js
* wallet is unclickable while creating
* reduce the min amount required to display the create wallet button to 0.01 ether
> Small fixes

- app/client/lib/appStart.js
Fixes a blank screen when loading the wallet interface with Ethereum Wallet.
> added @frozeman's fix

- app/client/styles/main.less
I’ve seen the sticky bar people. It’s terrible, horrible, it won’t stick. It’s failing, just failing. Approve this PR and I’ll build a great sticky bar, it will be a beautiful sticky bar, it will stick as soon as you scrolll up. Beautiful folks, simply beautiful.
> Make the Sticky Bar Sticky Again

- app/i18n/app.en.i18n.json
- app/i18n/wallet.en.i18n.json
minor typo and other text corrections
> minor typo and other text corrections

- app/client/templates/views/modals/eventInfo.html
- app/client/templates/views/modals/transactionInfo.html
fixes https://github.com/ethereum/mist/issues/2133
> update TX details link: testnet.etherscan.io -> ropsten.etherscan.io

- app/client/templates/views/contracts.js
fix https://github.com/ethereum/mist/issues/2173
> remove whitespaces from address on token.add()

- app/.meteor/versions
Trying to mitigate https://github.com/ethereum/mist/issues/2307
> update 'allow-deny' package to avert download timeout

- app/.meteor/versions
- app/client/styles/main.less
From:
To: 
Based on https://github.com/ethereum/mist/issues/1455#issuecomment-263080552
> Darken network info font

- app/.meteor/versions
- app/client/lib/helpers/helperFunctions.js
- app/client/templates/elements/executeContract.js
- app/client/templates/layout/header.js
- app/client/templates/views/modals/addToken.js
* Adds ens support to all address input elements
* On the watch token page, you can add tokens by just typing the three first letters, and it will add ‘.thetoken’ and fetch the rest of the information
> add ens support

- README.md
Pull Approve should only allow a merge once it has 2+ approvals from the maintainers.
> Let's test the new status check.

- app/client/templates/views/modals/qrCode.js
I am not entirely sure that this is the right place to put it as per MVC-pattern, but it seems appropriate.
> Make QR-code ERC-681 compliant

- app/client/lib/helpers/templateHelpers.js
- app/client/templates/elements/newAccountButton.html
- app/client/templates/views/dashboard.html
- Shows new account button on mist-enabled apps (Wallet, Mist)
- Hides new account button on non-mist apps (Metamask on chrome)
> Fixing account button on dashboard

- .gitignore
- README.md
- app/client/lib/appStart.js
- app/client/lib/ethereum/observeTokens.js
- app/client/templates/views/contracts.js
Often if the autoscan ends in errors it won't add any tokens, despite having found some. This makes autoscan adds tokens as it finds them. 
Not perfect, still have autoscan never finishing up and getting stuck on errors.
> Adds tokens as it finds them
