- app/client/templates/elements/compileContract.html
This changes enables the `^` symbol in the Solidity error messages to be positioned at the right point. Previously, line breaks were ignored and thus the position of the symbol was incorrect.
Note: I was not able to test this change.
> Use pre for solidity error message.

- app/client/templates/views/contracts.js
The function _addCustomContract_ used when adding custom contract has no default name.
If someone leaves the field _name_ empty, then he/she cannot edit the name or delete the custom contract directly on the UI because the text under _span.edit-name_ element is then empty string and nowhere to be clicked.
> add default name in function "addCustomContract"

- app/i18n/wallet.en.i18n.json
http://chriseth.github.io/browser-solidity/ shows:
"This application has moved to ethereum.github.io/browser-solidity and will no longer be updated here."
> Update "example of a custom token contract" URL

- app/client/styles/main.less
Also adjusts the margins so that the close and minimize buttons won’t interfere with the buttons on Mac. Useful for large screens.
> Make the wallet span the whole width of the app

- app/client/lib/ethereum/observeCustomContracts.js
- app/client/templates/elements/executeContract.js
- app/client/templates/views/send.js
Previously it was just picking the first account from the `owners`
array. This makes sure not only that you have that account, but that it
picks the highest balance you have
> When sending from multisig, makes sure you own the "from" account

- app/client/templates/elements/executeContract.js
Since `constant` contract functions automatically run when the
contract is viewed, we must initialize the input data during the
loading phase of the view, otherwise we will call the contract code
with zero arguments. Issue #216
> Immediately initialize inputs for `constant` contract functions.

- app/client/templates/elements/executeContract.js
We now append our callback function to a clone of the input data.
Since input data is already initialized, we can drop the `|| []`.
Issue #233.
> Invoke `constant` contract functions with a shallow copy of inputs.

- app/client/templates/elements/compileContract.js
- app/client/templates/views/send.js
[**From Solidity `v0.4.0` changelog:**](https://github.com/ethereum/solidity/blob/develop/Changelog.md#040-2016-09-08)
> Breaking Changes:
- Source files have to specify the compiler version they are compatible with using e.g. pragma solidity ^0.4.0; or pragma solidity >=0.4.0 <0.4.8; 
The current placeholder code will throw an error as soon as the compilation is triggered.
> contract placeholder: solidity ^0.4.0 requires pragma to be set

- app/client/lib/helpers/templateHelpers.js
Works properly with https://github.com/ethereum/mist/pull/1483 onwards.
> Mist api changes, backwards compatibility

- app/client/lib/appStart.js
- app/client/lib/helpers/helperFunctions.js
- app/client/templates/elements/compileContract.js
- app/client/templates/views/send.js
The Mist-API object `mist.solidity.version` will be available starting with `0.8.9`.
As current and older versions of Mist will query the wallet code from `wallet.ethereum.org` it will use `0.4.6` as soliditiy version (as currently used in `0.8.8`).
> Set placeholder contract's pragma version using Mist-API

- app/client/lib/thirdparty/coinbase-widget.js
- app/client/templates/elements/executeContract.js
- app/client/templates/views/account.js
This was requested by the coinbase guys:
“But, in a somewhat related change, we request that you modify the direct URL wherever you're using it to remove the `amount=` param, because we've redesigned the UX to default to a Coinbase-specified amount, currently set at $50. 
Removal of the `amount=` param will prevent your widget instance from showing $5 upon the initial screen, and then updating to $50 after a few seconds, which would be confusing and ugly.”
> Remove amount param from coinbase widget

- app/client/templates/views/send.js
As reported on: https://www.reddit.com/r/ethereum/comments/5rd4co/ethereum_wallet_sends_to/?st=IYNQ808M&sh=d42817a2
> Prevent user to transfer token to empty recipient

- app/client/lib/helpers/helperFunctions.js
Re-add caret operator after merged PR https://github.com/ethereum/mist/pull/1613.
> Add caret operator to contract example

- app/client/templates/elements/inputs/json.html
The interface doesn't specify whether addresses need quotes or not. I'm inferring from https://github.com/ethereum/meteor-dapp-wallet/issues/118 that address parameters need quotes.
> Addresses need quotes

- app/client/templates/views/account.js
fix https://github.com/ethereum/mist/issues/1722
Removing the `Tracker.afterFlush()` fixed the issue - no drawbacks I did witness. Though is this a valid fix, do I miss/does it break something?
> fix renaming bug

- app/client/templates/views/send.html
- app/client/templates/views/send.js
Fixes a bug a reddit user reported yesterday:
When selecting an account and instructing "send" via the zebra-token-list Ether will be selected instead of the token.
Also calling `{{reactiveData}}` changed the TemplateVars, thus rerun all `template.autorun()` instances, which might break the `if(!c.firstRun)` conditions.
> fixes token selection when sending via the zebra-token-list

- app/client/templates/elements/compileContract.js
When deploying a contract that was stored in localStorage (earlier last sessions) not editing it prior deploying will cause the fee calculation to be skipped.
How to reproduce:
1. Chose to deploy a new contract and paste some bigger contract like https://gist.github.com/luclu/5fe236b6bc03ff1c3a9932a1d3727d8b
1. Restart Ethereum Wallet
1. Try to deploy stored contract without editing it (fees should be miscalculated)
This PR will add the `0x` to the data, which will play nice with the stricter input validation from https://github.com/ethereum/mist/pull/2092. (which should be updated accordingly).
> fix gas calculation of stored contracts in localStorage

- app/client/templates/views/send.js
Fixes a bug where when directly switching from deploy view to the send view, the data field will still be populated.
> initialize send view correctly when switching from deploy view

- app/.meteor/packages
- app/i18n/wallet.fr.i18n.json
Makes a small correction to french translation, line 277: Expanse -> Ethereum (atom also killed some trailing whitespace)
Adds ecmascript to meteor packages as a ES6 template literal is used [here](https://github.com/ethereum/meteor-dapp-wallet/blob/develop/app/client/index.js#L27) resulting in build failure  
````
Bundling Meteor app...
Failed to execute "meteor build ../build --directory", exit code of #1
Errors prevented bundling:
While minifying app code:
/home/xocel/.meteor/packages/standard-minifier-js/.1.0.6.q82nzk++os+web.browser+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/minifier-js/node_modules/uglify-js/lib/parse.js:196:18:
Unexpected character '`'
````
Noticed ES6 has been added to related projects, I assume its intended to be added here also.
> Add ES6 support; correction to fr translation

- app/.meteor/packages
- app/client/index.js
`ecmascript` package introduced an indexeddb driver failure to load. 
This PR reverts `ecmascript` package, and the wallet is stable again.
> Temporarily removing ES6 support: fixing indexeddb driver bug

- app/client/templates/views/modals/addToken.html
> Changed placeholder text for Token Symbol input from $ to Token symbol

- app/.meteor/versions
- app/client/lib/ethereum/observeBlocks.js
- app/client/templates/elements/account.js
This PR fixes the creation of wallet contracts while using the Light Client.
It gets wallets that has transaction hash and does not have addresses and performs a getTransactionReceipt, trying to find that particular address.
It'll only work after https://github.com/ethereum/mist/pull/3265 has been released.
> Fix stuck creating wallets on LES

- app/client/lib/helpers/helperFunctions.js
From Solidity compiler 0.4.18 on, a warning will be fired when a method does not specify its visibility.
This PR adds `public` identifier to the constructor method.
> Adds method visibility in placeholder contract

- app/i18n/wallet.en.i18n.json
- app/i18n/wallet.pt.i18n.json
Message contained a typo; changed the message to align with ethereum/mist error message.
> Quick i18n language changes

- .pullapprove.yml
We're about to enforce at least two reviews per PR. The [Pull Approve](https://pullapprove.com) service helps us get there.
> Adding config file for pullapprove service
